strictness: medium
test-warnings: true
doc-warnings: false
member-warnings: false
inherits:
  - default
ignore-paths:
  - docs
  - end_effector
ignore-patterns:
  - (^|/)skip(this)?(/|$)
autodetect: true
max-line-length: 159

dodgy:
  run: true

mccabe:
  run: true
  options:
    max-complexity: 10

pycodestyle:
  run: true

pyflakes:
  disable:
    - F401

pylint:
  options:
    max-locals: 15
    max-returns: 6
    max-branches: 15
    max-statements: 60
    max-parents: 7
    max-attributes: 7
    min-public-methods: 1
    max-public-methods: 20
    max-module-lines: 1000
    max-line-length: 99
